services:
  app:
    build: ./app/
    image: w4w:latest
    container_name: app
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./db:/db
    networks:
      - app

  caddy:
    image: caddy:2.10.2
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app

networks:
  app:

volumes:
  caddy_data:
  caddy_config:

