@app_HostAddress = http://localhost:8080

GET {{app_HostAddress}}/products/
Accept: application/json

POST http://localhost:8080/products/
Content-Type: application/x-www-form-urlencoded
Accept: application/json
name=HttpTestName&categoryId=1&price=123.45&description=a%20cool%20description


###
